[connections.conn]
account = "ULBOYCP-GS10531"
user = "kanzaakram"
password = "Football.321"
warehouse = "COMPUTE_WH"
database = "breastcareTrials_db"
schema = "breastcare_schema"
client_session_keep_alive = true